---
- name: Ansible Playbook to create user group on windows server with control
  hosts: "dept_finance:&env_dev:&windows"
  gather_facts: no
  collections:
    - ansible.windows
  vars:
    win_group_name:
      - name: "aap_group_administrators"
        win_group_description: "Group for Ansible Automation Platform users"

    win_user_name: 
      - name: "aap_administrator"
        win_user_fullname: "Ansible Automation Platform Administrator user"
        win_user_description: "User for Ansible Automation Platform with administrative privileges"
        win_user_password: "P@ssw0rd123!"  # Ensure this meets Windows password complexity requirements
        win_user_never_expires: true
  tasks:
    - name: list all available users
      ansible.windows.win_powershell:
        script: |
          Get-LocalUser | Select-Object -ExpandProperty Name
      register: user_info

    - name: list existing user 
      ansible.builtin.debug:
        msg: "{{ user_info.output }}"

    - name: check if user exists
      ansible.builtin.set_fact:
        user_exists: "{{ win_user_name[0].name in user_info.output }}"

    - name: Create group
      ansible.windows.win_group:
        name: "{{ item.name }}"
        description: "{{ item.win_group_description }}"
        state: present
      loop: "{{ win_group_name }}"

    - name: Create user with administrative privileges
      ansible.windows.win_user:
        name: "{{ item.name }}"
        fullname: "{{ item.win_user_fullname }}"
        description: "{{ item.win_user_description }}"
        password: "{{ item.win_user_password }}"
        password_never_expires: "{{ item.win_user_never_expires }}"
        state: present
      loop: "{{ win_user_name }}"
      when: not user_exists

    - name: Add user to administrator group 
      ansible.windows.win_group_membership:
        name: "{{ item.name }}"
        members:
          - "{{ win_user_name[0].name }}"
        state: present
      loop: "{{ win_group_name }}"
      

    - name: list all members of the group
      ansible.windows.win_powershell:
        script: |
          Get-LocalGroupMember -Group "{{ win_group_name[0].name }}" | Select-Object -ExpandProperty Name
      register: group_members_info  
    
    - name: Display group members
      ansible.builtin.debug:
        msg: "Members of group {{ win_group_name[0].name }}: {{ group_members_info.output }}"
    
    - name: liste all available groups and users 
      ansible.windows.win_powershell:
        script: |
          Get-LocalGroup | Select-Object -ExpandProperty Name
          Get-LocalUser | Select-Object -ExpandProperty Name
        register: group_info

    - name: Display groups and users
      ansible.builtin.debug:
        msg: "{{ group_info.output }}"